server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlite:chat-server.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    show-sql: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

chat:
  storage:
    path: uploads
